#ifndef CONSTANTS_H
#define CONSTANTS_H

//Colores
#define GREEN QColor(50,175,50)
#define GREEN_H QString("#32AF32")
#define RED QColor(255,0,0)
#define SOFT_RED QColor(255,40,40)
#define SOFT_RED_H QString("#FF2828")
#define YELLOW QColor(255,255,0)
#define WHITE QColor(255,255,255)
#define BLACK QColor(0,0,0)
#define BLUE QColor(0,191,255)
#define VIOLET QColor(186,85,211)
#define ORANGE QColor(255,165,0)

//Fuentes
#define HS_FONT "Belwe Bd BT"
#define LG_FONT "Luckiest Guy"


//Secretos
//PALADIN
#define HAND_OF_SALVATION QString("BCON_012")
#define AVENGE QString("FP1_020")
#define NOBLE_SACRIFICE QString("EX1_130")
#define REPENTANCE QString("EX1_379")
#define REDEMPTION QString("EX1_136")
#define SACRED_TRIAL QString("LOE_027")
#define EYE_FOR_AN_EYE QString("EX1_132")
#define GETAWAY_KODO QString("CFM_800")
#define COMPETITIVE_SPIRIT QString("AT_073")
#define HIDDEN_WISDOM QString("GIL_903")
#define AUTODEFENSE_MATRIX QString("BOT_908")
#define NEVER_SURRENDER QString("DAL_570")
#define OH_MY_YOGG QString("DMF_236")
#define RECKONING QString("CS3_016")
#define GALLOPING_SAVIOR QString("BAR_550")
#define JUDGMENT_OF_JUSTICE QString("WC_033")

//HUNTER
#define FREEZING_TRAP QString("EX1_611")
#define EXPLOSIVE_TRAP QString("EX1_610")
#define BEAR_TRAP QString("AT_060")
#define SNIPE QString("EX1_609")
#define DART_TRAP QString("LOE_021")
#define VENOMSTRIKE_TRAP QString("ICC_200")
#define CAT_TRICK QString("KAR_004")
#define MISDIRECTION QString("EX1_533")
#define HIDDEN_CACHE QString("CFM_026")
#define SNAKE_TRAP QString("EX1_554")
#define WANDERING_MONSTER QString("LOOT_079")
#define RAT_TRAP QString("GIL_577")
#define PRESSURE_PLATE QString("ULD_152")
#define PACK_TACTICS QString("BT_203")
#define OPEN_THE_CAGES QString("DMF_123")
#define ICE_TRAP QString("AV_226")
#define EMERGENCY_MANEUVERS QString("TSC_929")
#define MOTION_DENIED QString("MAW_010")
#define ZOMBEEEES QString("NX2_013")
#define HIDDEN_MEANING QString("JAM_003")
#define BAIT_AND_SWITCH QString("TTN_504")

//MAGE
#define FROZEN_CLONE QString("ICC_082")
#define MIRROR_ENTITY QString("EX1_294")
#define DDUPLICATE QString("FP1_018")
#define ICE_BARRIER QString("EX1_289")
#define POTION_OF_POLIMORPH QString("CFM_620")
#define EFFIGY QString("AT_002")
#define VAPORIZE QString("EX1_594")
#define COUNTERSPELL QString("EX1_287")
#define MANA_BIND QString("UNG_024")
#define SPLITTING_IMAGE QString("TRL_400")
#define SPELLBENDER QString("tt_010")
#define ICE_BLOCK QString("EX1_295")
#define EXPLOSIVE_RUNES QString("LOOT_101")
#define FLAME_WARD QString("ULD_239")
#define NETHERWIND_PORTAL QString("BT_003")
#define RIGGED_FAIRE_GAME QString("DMF_107")
#define OASIS_ALLY QString("BAR_812")
#define VENGEFUL_VISAGE QString("REV_516")
#define OBJECTION QString("MAW_006")

//ROGUE
#define CHEAT_DEATH QString("LOOT_204")
#define SUDDEN_BETRAYAL QString("LOOT_210")
#define EVASION QString("LOOT_214")
#define AMBUSH QString("BT_707")
#define BAMBOOZLE QString("BT_042")
#define DIRTY_TRICKS QString("BT_709")
#define PLAGIARIZE QString("SCH_706")
#define SHADOW_CLONE QString("DMF_513")
#define SHENANIGANS QString("YOP_017")
#define DOUBLE_CROSS QString("REV_825")
#define KIDNAP QString("REV_828")
#define STICKY_SITUATION QString("REV_827")
#define PERJURY QString("MAW_018")



//Cartas
#define THE_COIN "GAME_005"
//LEGACY - EXPERT1
#define SWIPE "CS2_012"
#define FAR_SIGHT "CS2_053"
#define TRUESILVER_CHAMPION "CS2_097"
#define FLOODSAIL_DECKHAND "CS3_008"
#define TAELAN_FORDRING "CS3_024"
#define MALYGOS_THE_SPELLWEAVER "CS3_034"
#define GLADIATORS_LONGBOW "DS1_188"
#define LIGHTWARDEN "EX1_001"
#define ACOLYTE_OF_PAIN "EX1_007"
#define MAD_BOMBER "EX1_082"
#define LOREWALKER_CHO "EX1_100"
#define INNERVATE "EX1_169"
#define ARCANE_MISSILES "EX1_277"
#define SENSE_DEMONS "EX1_317"
#define HOLY_WRATH "EX1_365"
#define SWORD_OF_JUSTICE "EX1_366"
#define AVENGING_WRATH "EX1_384"
#define GURUBASHI_BERSERKER "EX1_399"
#define ARMORSMITH "EX1_402"
#define GOREHOWL "EX1_411"
#define GRIMSCALE_ORACLE "EX1_508"
#define EXPLOSIVE_SHOT "EX1_537"
#define SEA_GIANT "EX1_586"
#define FROTHING_BERSEKER "EX1_604"
#define SHADOWFLAME "EX1_303"
#define CAPTAINS_PARROT "NEW1_016"
#define KNIFE_JUGGLER "NEW1_019"
#define LEOKK "NEW1_033"
//TAVERNS_OF_TIME
#define GRASP_THE_FUTURE "TOT_103"
#define TIMEBOUND_GIANT "TOT_110"
#define TIMEWAY_WANDERER "TOT_116"
//NAXX
#define MAD_SCIENTIST "FP1_004"
//GVG
#define GOBLIN_BLASTMAGE "GVG_004"
#define SIEGE_ENGINE "GVG_086"
#define MADDER_BOMBER "GVG_090"
#define GNOMISH_EXPERIMENTER "GVG_092"
#define CLOCKWORK_GIANT "GVG_121"
//BRM
#define FLAMEWAKER "BRM_002"
#define IMP_GANG_BOSS "BRM_006"
#define AXE_FLINGER "BRM_016"
#define DRAGON_EGG "BRM_022"
#define MAJORDOMO_EXECUTUS "BRM_027"
#define MAJORDOMO_EXECUTUS_HERO "BRM_027h"
//TGT
#define WRATHGUARD "AT_026"
#define POWERSHOT "AT_056"
#define KINGS_ELEKK "AT_058"
#define ACIDMAW "AT_063"
#define VARIAN_WRYNN "AT_072"
#define ARMORED_WARHORSE "AT_108"
#define THE_SKELETON_KNIGHT "AT_128"
//LOE
#define ENGRAVE "LOE_104"
//OG
#define FORBIDDEN_ANCIENT "OG_051"
#define THISTLE_TEA "OG_073"
#define FORBIDDEN_FLAME "OG_086"
#define FORBIDDEN_SHAPING "OG_101"
#define DARKSHIRE_COUNCILMAN "OG_113"
#define FORBIDDEN_RITUAL "OG_114"
#define SPREADING_MADNESS "OG_116"
#define SHIFTER_ZERUS "OG_123"
#define NERUBIAN_PROPHET "OG_138"
#define FORBIDDEN_HEALING "OG_198"
#define HALLAZEAL_THE_ASCENDED "OG_209"
#define ADDLED_GRIZZLY "OG_313"
#define POLLUTED_HOARDER "OG_323"
//KARA
#define THE_CURATOR "KAR_061"
#define PRINCE_MALCHEZAAR "KAR_096"
//GANGS
#define SMUGGLERS_CRATE "CFM_334"
#define SHAKY_ZYPGUNNER "CFM_336"
#define KABAL_CHEMIST "CFM_619"
#define GREATER_ARCANE_MISSILES "CFM_623"
#define COUNTERFEIT_COIN "CFM_630"
#define SECOND_RATE_BRUISER "CFM_652"
#define DON_HANCHO "CFM_685"
#define STOLEN_GOODS "CFM_752"
#define GRIMY_GADGETEER "CFM_754"
#define UNLICENSED_APOTHECARY "CFM_900"
#define SMALLTIME_RECRUITS "CFM_905"
//UNGORO
#define ARCANOLOGIST "UNG_020"
#define VOLCANO "UNG_025"
#define MIMIC_POD "UNG_060"
#define BITTERTIDE_HYDRA "UNG_087"
#define LIVING_MANA "UNG_111"
#define BRIGHTEYED_SCOUT "UNG_113"
#define BLOODBLOOM "UNG_832"
#define GRIEVOUS_BITE "UNG_910"
#define TOLVIR_WARDEN "UNG_913"
#define MOLTEN_BLADE "UNG_929"
#define PRIMORDIAL_GLYPH "UNG_941"
#define METEOR "UNG_955"
//ICECROWN
#define ICE_FISHING "ICC_089"
#define FORGE_OF_SOULS "ICC_281"
#define THRALL_DEATHSEER "ICC_481"
#define HOWLING_COMMANDER "ICC_801"
#define CRYPT_LORD "ICC_808"
#define VALEERA_THE_HOLLOW "ICC_827"
#define DEATHSTALKER_REXXAR "ICC_828"
#define UTHER_OF_THE_EBON_BLADE "ICC_829"
#define SHADOWREAPER_ANDUIN "ICC_830"
#define BLOODREAVER_GULDAN "ICC_831"
#define MALFURION_THE_PESTILENT "ICC_832"
#define FROST_LICH_JAINA "ICC_833"
#define SCOURGELORD_GARROSH "ICC_834"
//LOOTAPALOOZA
#define PSYCHIC_SCREAM "LOOT_008"
#define CAVERN_SHINYFINDER "LOOT_033"
#define LESSER_JASPER_SPELLSTONE "LOOT_051"
#define SHIFTING_SCROLL "LOOT_104"
#define CORRIDOR_CREEPER "LOOT_149"
#define RAVEN_FAMILIAR "LOOT_170"
#define LESSER_MITHRIL_SPELLSTONE "LOOT_203"
#define ELVEN_MINSTREL "LOOT_211"
#define CANDLESHOT "LOOT_222"
#define KOBOLD_APPRENTICE "LOOT_347"
#define UNSTABLE_EVOLUTION "LOOT_504"
#define UNSTABLE_EVOLUTION_TOKEN "LOOT_504t"
#define TOLINS_GOBLET "LOOT_998h"
#define WONDROUS_WAND "LOOT_998l"
//GILNEAS
#define CHAMELEOS "GIL_142"
#define CINDERSTORM "GIL_147"
#define BOOK_OF_SPECTERS "GIL_548"
#define CURSED_CASTAWAY "GIL_557"
#define COUNTESS_ASHMORE "GIL_578"
#define TOWN_CRIER "GIL_580"
#define SANDBINDER "GIL_581"
#define WITCHWOOD_PIPER "GIL_584"
#define DOLLMASTER_DORIAN "GIL_620"
#define BOGSHAPER "GIL_807"
//BOOMSDAY
#define ACADEMIC_ESPIONAGE "BOT_087"
#define ELEMENTARY_REACTION "BOT_093"
#define LUNAS_POCKET_GALAXY "BOT_257"
#define STORM_CHASER "BOT_291"
#define JUICY_PSYCHMELON "BOT_404"
#define DREAMPETAL_FLORIST "BOT_423"
#define PRISMATIC_LENS "BOT_436"
#define DEAD_RINGER "BOT_509"
#define MULCHMUNCHER "BOT_523"
#define SUBJECT_9 "BOT_573"
#define METEOROLOGIST "BOT_601"
#define CRYSTOLOGY "BOT_909"
//TROLL
#define HAUNTING_VISIONS "TRL_058"
#define SPIRIT_OF_THE_FROG "TRL_060"
#define RAIDING_PARTY "TRL_124"
#define CANNON_BARRAGE "TRL_127"
#define PREDATORY_INSTINCTS "TRL_244"
#define BWONSAMDI_THE_DEAD "TRL_260"
#define AKALI_THE_RHINO "TRL_329"
#define MASTERS_CALL "TRL_339"
#define GRAVE_HORROR "TRL_408"
#define RABBLE_BOUNCER "TRL_515"
#define MURLOC_TASTYFIN "TRL_520"
#define DEMONBOLT "TRL_555"
//DALARAN
#define ARCANE_FLETCHER "DAL_372"
#define URSATRON "DAL_604"
#define KALECGOS "DAL_609"
#define FORBIDDEN_WORDS "DAL_723"
#define CALL_TO_ADVENTURE "DAL_727"
#define JEPETTO_JOYBUZZ "DAL_752"
#define SOLDIER_OF_FORTUNE "DAL_771"
//ULDUM
#define MOGU_FLESHSHAPER "ULD_169"
#define RENO_THE_RELICOLOGIST "ULD_238"
#define SALHETS_PRIDE "ULD_438"
#define ANCIENT_MYSTERIES "ULD_726"
//DRAGONS
#define DIVING_GRYPHON "DRG_010"
#define ANCHARRR "DRG_025"
#define NECRIUM_APOTHECARY "DRG_031"
#define STOWAWAY "DRG_034"
#define TENTACLED_MENACE "DRG_084"
#define TRANSMOGRIFIER "DRG_092"
#define KRONX_DRAGONHOOF "DRG_099"
#define DARK_SKIES "DRG_204"
#define EMBIGGEN "DRG_315"
#define ROLLING_FIREBALL "DRG_321"
#define ELEMENTAL_ALLIES "DRG_324"
#define GALADROND_THE_NIGHTMARE "DRG_610"
#define GALADROND_THE_NIGHTMARE2 "DRG_610t2"
#define GALADROND_THE_NIGHTMARE3 "DRG_610t3"
#define GALADROND_THE_UNBREAKABLE "DRG_650"
#define GALADROND_THE_UNBREAKABLE2 "DRG_650t2"
#define GALADROND_THE_UNBREAKABLE3 "DRG_650t3"
//YEAR_OF_THE_DRAGON
#define WAXMANCY "YOD_018"
#define FRENZIED_FELWING "YOD_032"
//BLACK_TEMPLE
#define STARSCRYER "BT_014"
#define VASHJ_PRIME "BT_109t"
#define CORSAIR_CACHE "BT_124"
#define IMPRISONED_SATYR "BT_127"
#define FUNGAL_FORTUNES "BT_128"
#define BLOODBOIL_BRUTE "BT_138"
#define NAGRAND_SLAM "BT_163"
#define SCAVENGERS_INGENUITY "BT_213"
#define THE_DARK_PORTAL "BT_302"
#define PRIESTESS_OF_FURY "BT_493"
#define SKULL_OF_GULDAN "BT_601"
#define SCAVENGING_SHIVARRA "BT_732"
#define EYE_BEAM "BT_801"
//SCHOLOMANCE
#define DEVOUT_PUPIL "SCH_139"
#define FLESH_GIANT "SCH_140"
#define DEMONIC_STUDIES "SCH_158"
#define DRACONIC_STUDIES "SCH_233"
#define ATHLETIC_STUDIES "SCH_237"
#define FIREBRAND "SCH_241"
#define PRIMORDIAL_STUDIES "SCH_270"
#define CARRION_STUDIES "SCH_300"
#define NATURE_STUDIES "SCH_333"
#define COMBUSTION "SCH_348"
#define FEL_GUARDIANS "SCH_357"
#define DOUBLE_JUMP "SCH_422"
#define LIGHTNING_BLOOM "SCH_427"
#define CUTTING_CLASS "SCH_623"
//DARKMOON_FAIRE
#define INSIGHT "DMF_054"
#define INSIGHT_CORRUPT "DMF_054t"
#define GHUUN_THE_BLOOD_GOD "DMF_056"
#define UMBRAL_OWL "DMF_060"
#define CLAW_MACHINE "DMF_069"
#define MASK_OF_CTHUN "DMF_103"
#define FREE_ADMISSION "DMF_113"
#define PALM_READING "DMF_187"
#define REDSCALE_DRAGONTAMER "DMF_194"
#define EYE_OF_CTHUN "DMF_254t3"
#define HEART_OF_CTHUN "DMF_254t4"
#define BODY_OF_CTHUN "DMF_254t5"
#define MAW_OF_CTHUN "DMF_254t7"
#define SWINDLE "DMF_515"
#define GRAND_EMPRESS_SHEKZARA "DMF_516"
#define MINEFIELD "DMF_522"
#define RINGMASTER_WHATLEY "DMF_525"
#define STAGE_DIVE "DMF_526"
#define STAGE_DIVE_CORRUPT "DMF_526a"
#define TENT_TRASHER "DMF_528"
#define DUNK_TANK "DMF_701"
#define CAGEMATCH_CUSTODIAN "DMF_704"
#define ILLIDARI_STUDIES "YOP_001"
#define HYSTERIA "YOP_006"
#define MANA_BISCUIT "YOP_019t"
#define BOLA_SHOT "YOP_027"
//THE_BARRENS
#define WARSONG_WRANGLER "BAR_037"
#define PRIMORDIAL_PROTECTOR "BAR_042"
#define TINYFINS_CARAVAN "BAR_043"
#define POWER_WORD_FORTITUDE "BAR_308"
#define DEVOURING_PLAGUE "BAR_311"
#define EFFICIENT_OCTOBOT "BAR_320"
#define VENGEFUL_SPIRIT "BAR_328"
#define TUSKPIERCER "BAR_330"
#define LIVING_SEED "BAR_536"
#define REFRESHING_SPRING_WATER "BAR_542"
#define BARAK_KODOBANE "BAR_551"
#define SCABBS_CUTTERBUTTER "BAR_552"
#define KINDLING_ELEMENTAL "BAR_854"
#define KNIGHT_OF_ANOINTMENT "BAR_873"
#define NORTHWATCH_COMMANDER "BAR_876"
#define GRIMOIRE_OF_SACRIFICE "BAR_910"
#define FROSTWEAVE_DUNGEONEER "WC_805"
#define CLERIC_OF_ANSHE "WC_803"
#define SHROUD_OF_CONCEALMENT "WC_016"
#define DEVOUT_DUNGEONEER "WC_013"
#define PRIMAL_DUNGEONEER "WC_005"
//STORMWIND
#define CELESTIAL_INK_SET "SW_001"
#define RUNED_MITHRIL_ROD "SW_003"
#define AUCTIONHOUSE_GAVEL "SW_025"
#define RAID_THE_DOCKS "SW_028"
#define HARBOR_SCAMP "SW_029"
#define GRANITE_FORGEBORN "SW_032"
#define IREBOUND_BRUTE "SW_037"
#define SIGIL_OF_ALACRITY "SW_041"
#define FELGORGER "SW_043"
#define GOLDSHIRE_GNOLL "SW_062"
#define VARIAN_KING_OF_STORMWIND "SW_081"
#define INVESTMENT_OPPORTUNITY "SW_095"
#define CLUMSY_COURIER "SW_109"
#define SANCTUM_CHANDLER "SW_111"
#define ENCUMBERED_PACK_MULE "SW_306"
#define ALLIANCE_BANNERMAN "SW_315"
#define SKETCHY_INFORMATION "SW_405"
#define SI7_SKULKER "SW_418"
#define TWILIGHT_DECEPTOR "SW_444"
#define SORCERERS_GAMBIT "SW_450"
#define LEATHERWORKING_KIT "SW_457"
#define DEFIAS_BLASTFISHER "DED_007"
#define MAN_THE_CANNONS "DED_518"
#define MADDEST_BOMBER "DED_521"
#define DEEPWATER_EVOKER "DED_516"
#define HULLBREAKER "DED_505"
//ALTERAC_VALLEY
#define FULLBLOWN_EVIL "AV_285"
#define SHIELD_SHATTER "AV_108"
#define SHIVERING_SORCERESS "AV_114"
#define TO_THE_FRONT "AV_119"
#define FROSTWOLF_WARMASTER "AV_134"
#define STORMPIKE_MARSHAL "AV_135"
#define LOKHOLAR_THE_ICE_LORD "AV_141t"
#define URZUL_GIANT "AV_265"
#define FROSTSABER_MATRIARCH "AV_291"
#define PRIDE_SEEKER "AV_296"
#define WILDPAW_GNOLL "AV_298"
#define STORMPIKE_BATTLE_RAM "AV_334"
#define CERATHINE_FLEETRUNNER "AV_403"
#define RECONNAISSANCE "AV_710"
#define HERALD_OF_LOKHOLAR "AV_101"
#define DUN_BALDAR_BUNKER "AV_147"
#define VITALITY_SURGE "AV_213"
#define FELFIRE_IN_THE_HOLE "AV_281"
#define BALINDA_STONEHEARTH "AV_284"
#define CAPTURE_COLDTOOTH_MINE "AV_295"
#define SHADOW_WORD_DEVOUR "AV_324"
#define SPIRIT_GUIDE "AV_328"
#define STONEHEARTH_VINDICATOR "AV_343"
#define AXE_BERSERKER "AV_565"
#define DONT_STAND_IN_THE_FIRE "ONY_011"
#define BRACING_COLD "ONY_013"
#define SMOKESCREEN "ONY_031"
#define HORN_OF_WRATHION "ONY_017"
//THE_SUNKEN_CITY
#define SEAFLOOR_GATEWAY "TSC_055"
#define THE_GARDENS_GRACE "TSC_061"
#define WHISPERS_OF_THE_DEEP "TSC_211"
#define WAYWARD_SAGE "TSC_217"
#define GREENTHUMB_GARDENER "TSC_652"
#define MURKWATER_SCRIBE "TSC_823"
#define NAGA_GIANT "TSC_829"
#define EXCAVATION_SPECIALIST "TSC_911"
#define SWIFTSCALE_TRICKSTER "TSC_936"
#define FROM_THE_DEPTHS "TSC_940"
#define GORLOC_RAVAGER "TSC_034"
#define SEAFLOOR_GATEWAY "TSC_055"
#define CONCHS_CALL "TSC_072"
#define RADAR_DETECTOR "TSC_079"
#define CUTLASS_COURIER "TSC_085"
#define ABYSSAL_DEPTHS "TSC_608"
#define TRENCH_SURVEYOR "TSC_642"
#define AQUATIC_FORM "TSC_654"
#define SWITCHEROO "TSC_702"
#define CRUSHCLAW_ENFORCER "TSC_826"
#define GONE_FISHIN "TSC_916"
#define LIGHTRAY "TID_077"
#define FOSSIL_FANATIC "TID_704"
//REVENDRETH
#define PLANTED_EVIDENCE "REV_313"
#define RELIC_OF_DIMENSIONS "REV_508"
#define GIGANTOTEM "REV_838"
#define SERRATED_BONE_SPIKE "REV_939"
#define MURLOCULA "REV_957"
#define DEATH_BLOSSOM_WHOMPER "REV_310"
#define NIGHTSHADE_BUD "REV_311"
#define SESSELIE_OF_THE_FAE_COURT "REV_319"
#define WIDOWBLOOM_SEEDSMAN "REV_318"
#define CONQUERORS_BANNER "REV_931"
#define DOOR_OF_SHADOWS "REV_938"
#define SERVICE_BELL "REV_948"
#define SCRIBBLING_STENOGRAPHER "MAW_020"
#define ORDER_IN_THE_COURT "MAW_016"
#define WEAPONS_EXPERT "MAW_029"
//RETURN_OF_THE_LICH_KING
#define SOUL_BARRAGE "RLK_534"
#define HORN_OF_WINTER "RLK_042"
#define STITCHED_GIANT "RLK_744"
#define ANUBREKHAN "RLK_659"
#define CRYPT_KEEPER "RLK_651"
#define LIGHT_OF_THE_PHOENIX "RLK_603"
#define BONELORD_FROSTWHISPER "RLK_591"
#define SHADOW_OF_DEMISE "RLK_567"
#define ROTTEN_RODENT "RLK_216"
#define VENGEFUL_WALLOPER "RLK_213"
#define FLESH_BEHEMOTH "RLK_830"
#define ARCANE_QUIVER "RLK_817"
#define RUNEFORGING "RLK_715"
#define LAST_STAND "RLK_601"
#define PRESCIENCE "RLK_553"
#define HARBINGER_OF_WINTER "RLK_511"
#define OVERSEER_FRIGIDARA "RLK_224"
#define MARK_OF_SCORN "RLK_206"
#define HOWLING_BLAST "RLK_015"
#define PRIESTESS_VALISHJ "TSC_828"
#define LIFE_FROM_DEATH "NX2_011"
#define LOST_EXARCH "NX2_032"
#define THE_PURATOR "NX2_023"
#define TRINKET_TRACKER "NX2_014"
//BATTLE_OF_THE_BANDS
#define GUITAR_SOLOIST "ETC_026"
#define BEATBOXER "ETC_072"
#define MC_BLINGTRON "ETC_078"
#define VOID_VIRTUOSO "ETC_081"
#define COWBELL_SOLOIST "ETC_101"
#define HIPSTER "ETC_103"
#define FREQUENCY_OSCILLATOR "ETC_106"
#define ROCK_MASTER_BOONE "ETC_121"
#define RUSH_THE_STAGE "ETC_200"
#define VOLUME_UP "ETC_205"
#define KANGOR_DANCING_KING "ETC_329"
#define LOVE_EVERLASTING "ETC_335"
#define HEARTTHROB "ETC_339"
#define ALTERED_CHORD "ETC_356"
#define CHORUS_RIFF "ETC_364"
#define INZAH "ETC_371"
#define PEACEFUL_PIPER "ETC_375"
#define SUMMER_FLOWERCHILD "ETC_376"
#define SPREAD_THE_WORD "ETC_384"
#define ZOK_FOGSNOUT "ETC_386"
#define DJ_MANASTORM "ETC_395"
#define THE_ONE_AMALGAM_BAND "ETC_409"
#define SNAKEBITE "ETC_410"
#define INSTRUMENT_TECH "ETC_418"
#define METROGNOME "ETC_422"
#define CAGE_HEAD "ETC_526"
#define TONY_KING_OF_PIRACY "ETC_541"
#define JAZZ_BASS "ETC_813"
#define MISTER_MUKLA "ETC_836"
#define BIG_DREAMS "ETC_838"
#define BANJOSAUR "ETC_840"
#define ABYSSAL_BASSIST "JAM_016"
#define BLOOD_TREANT "JAM_028"
#define FANOTTEM_LORD_OF_THE_OPERA "JAM_030"
#define COSTUMED_SINGER "JAM_001"
#define MAGATHA_BANE_OF_MUSIC "JAM_036"
//TITANS
#define SIF "TTN_071"
#define IMPRISONED_HORROR "TTN_462"
#define MINOTAUREN "TTN_466"
#define RADEN "TTN_481"
#define LOKEN_JAILER_OF_YOGGSARON "TTN_487"
#define ANGRY_HELHOUND "TTN_713"
#define HODIR_FATHER_OF_GIANTS "TTN_752"
#define RAVENOUS_KRAKEN "TTN_754"
#define ODYN_PRIME_DESIGNATE "TTN_811"
#define THORIM_STORMLORD "TTN_835"
#define JOTUN_THE_ETERNAL "TTN_842"
#define TYR "TTN_857"
#define ASTRAL_SERPENT "TTN_907"
#define MIMIRON_THE_MASTERMIND "TTN_920"
#define FREYA_KEEPER_OF_NATURE "TTN_940"
#define BELLOWING_FLAMES "TTN_753"
#define BELLOWING_FLAMES_FORGED "TTN_753t"
#define MORTAL_ERADICATION "TTN_460"
#define XB488_DISPOSALBOT "TTN_458"
#define XB488_DISPOSALBOT_FORGED "TTN_458t"
#define WISDOM_OF_NORGANNON "TTN_085"
#define STARSTRUNG_BOW "TTN_088"
#define AQUA_ARCHIVIST "TTN_095"
#define TRAM_OPERATOR "TTN_723"
#define CULTIVATION "TTN_954"
#define STEAM_GUARDIAN "TTN_468"
#define SHARPEYED_SEEKER "TTN_712"
#define PIT_STOP "TTN_728"
#define EMBRACE_OF_NATURE "TTN_951"
#define CREATION_PROTOCOL_FORGED "TTN_430t"
#define JUDGE_UNWORTHY "TTN_853"










#endif // CONSTANTS_H
