#ifndef CONSTANTS_H
#define CONSTANTS_H

//Colores
#define GREEN QColor(50,175,50)
#define GREEN_H QString("#32AF32")
#define RED QColor(255,0,0)
#define SOFT_RED QColor(255,40,40)
#define SOFT_RED_H QString("#FF2828")
#define YELLOW QColor(255,255,0)
#define WHITE QColor(255,255,255)
#define BLACK QColor(0,0,0)
#define BLUE QColor(0,191,255)
#define VIOLET QColor(186,85,211)
#define ORANGE QColor(255,165,0)

//Fuentes
#define HS_FONT "Belwe Bd BT"
#define LG_FONT "Luckiest Guy"


//Secretos
#define HAND_OF_SALVATION QString("BCON_012")
#define AVENGE QString("FP1_020")
#define NOBLE_SACRIFICE QString("EX1_130")
#define REPENTANCE QString("EX1_379")
#define REDEMPTION QString("EX1_136")
#define SACRED_TRIAL QString("LOE_027")
#define EYE_FOR_AN_EYE QString("EX1_132")
#define GETAWAY_KODO QString("CFM_800")
#define COMPETITIVE_SPIRIT QString("AT_073")
#define HIDDEN_WISDOM QString("GIL_903")
#define AUTODEFENSE_MATRIX QString("BOT_908")

#define FREEZING_TRAP QString("EX1_611")
#define EXPLOSIVE_TRAP QString("EX1_610")
#define BEAR_TRAP QString("AT_060")
#define SNIPE QString("EX1_609")
#define DART_TRAP QString("LOE_021")
#define VENOMSTRIKE_TRAP QString("ICC_200")
#define CAT_TRICK QString("KAR_004")
#define MISDIRECTION QString("EX1_533")
#define HIDDEN_CACHE QString("CFM_026")
#define SNAKE_TRAP QString("EX1_554")
#define WANDERING_MONSTER QString("LOOT_079")
#define RAT_TRAP QString("GIL_577")

#define FROZEN_CLONE QString("ICC_082")
#define MIRROR_ENTITY QString("EX1_294")
#define DDUPLICATE QString("FP1_018")
#define ICE_BARRIER QString("EX1_289")
#define POTION_OF_POLIMORPH QString("CFM_620")
#define EFFIGY QString("AT_002")
#define VAPORIZE QString("EX1_594")
#define COUNTERSPELL QString("EX1_287")
#define MANA_BIND QString("UNG_024")
#define SPELLBENDER QString("tt_010")
#define ICE_BLOCK QString("EX1_295")
#define EXPLOSIVE_RUNES QString("LOOT_101")

#define CHEAT_DEATH QString("LOOT_204")
#define SUDDEN_BETRAYAL QString("LOOT_210")
#define EVASION QString("LOOT_214")

//Cartas
#define MAD_SCIENTIST "FP1_004"
#define THE_COIN "GAME_005"
#define SWIPE "CS2_012"
#define ENGRAVE "LOE_104"
#define FROTHING_BERSEKER "EX1_604"
#define ARMORSMITH "EX1_402"
#define KNIFE_JUGGLER "NEW1_019"
#define ADDLED_GRIZZLY "OG_313"
#define DARKSHIRE_COUNCILMAN "OG_113"
#define ACIDMAW "AT_063"
#define WRATHGUARD "AT_026"
#define IMP_GANG_BOSS "BRM_006"
#define AXE_FLINGER "BRM_016"
#define DRAGON_EGG "BRM_022"
#define ACOLYTE_OF_PAIN "EX1_007"
#define GURUBASHI_BERSERKER "EX1_399"
#define LIGHTWARDEN "EX1_001"
#define TRUESILVER_CHAMPION "CS2_097"
#define GOREHOWL "EX1_411"
#define LEOKK "NEW1_033"
#define LOREWALKER_CHO "EX1_100"
#define NERUBIAN_PROPHET "OG_138"
#define THE_SKELETON_KNIGHT "AT_128"
#define GLADIATORS_LONGBOW "DS1_188"
#define EXPLOSIVE_SHOT "EX1_537"
#define POWERSHOT "AT_056"
#define ARMORED_WARHORSE "AT_108"
#define SWORD_OF_JUSTICE "EX1_366"
#define GRIMSCALE_ORACLE "EX1_508"
#define SIEGE_ENGINE "GVG_086"
#define POLLUTED_HOARDER "OG_323"
#define FLAMEWAKER "BRM_002"
#define MAD_BOMBER "EX1_082"
#define MADDER_BOMBER "GVG_090"
#define SPREADING_MADNESS "OG_116"
#define ARCANE_MISSILES "EX1_277"
#define AVENGING_WRATH "EX1_384"
#define GOBLIN_BLASTMAGE "GVG_004"
#define SMUGGLERS_CRATE "CFM_334"
#define STOLEN_GOODS "CFM_752"
#define SHAKY_ZYPGUNNER "CFM_336"
#define GRIMY_GADGETEER "CFM_754"
#define DON_HANCHO "CFM_685"
#define INNERVATE "EX1_169"
#define COUNTERFEIT_COIN "CFM_630"
#define KABAL_CHEMIST "CFM_619"
#define MIMIC_POD "UNG_060"
#define THISTLE_TEA "OG_073"
#define BITTERTIDE_HYDRA "UNG_087"
#define SENSE_DEMONS "EX1_317"
#define HOLY_WRATH "EX1_365"
#define ICE_FISHING "ICC_089"
#define FORGE_OF_SOULS "ICC_281"
#define HOWLING_COMMANDER "ICC_801"
#define THE_CURATOR "KAR_061"
#define ARCANOLOGIST "UNG_020"
#define BRIGHTEYED_SCOUT "UNG_113"
#define TOLVIR_WARDEN "UNG_913"
#define SMALLTIME_RECRUITS "CFM_905"
#define MOLTEN_BLADE "UNG_929"
#define SHIFTER_ZERUS "OG_123"
#define CHAMELEOS "GIL_142"
#define WONDROUS_WAND "LOOT_998l"
#define TOLINS_GOBLET "LOOT_998h"
#define KOBOLD_APPRENTICE "LOOT_347"
#define RAVEN_FAMILIAR "LOOT_170"
#define CAVERN_SHINYFINDER "LOOT_033"
#define ELVEN_MINSTREL "LOOT_211"
#define SHIFTING_SCROLL "LOOT_104"
#define CORRIDOR_CREEPER "LOOT_149"
#define CANDLESHOT "LOOT_222"
#define UNLICENSED_APOTHECARY "CFM_900"
#define CRYPT_LORD "ICC_808"
#define FORBIDDEN_SHAPING "OG_101"
#define FORBIDDEN_FLAME "OG_086"
#define FORBIDDEN_HEALING "OG_198"
#define FORBIDDEN_RITUAL "OG_114"
#define FORBIDDEN_ANCIENT "OG_051"
#define UNSTABLE_EVOLUTION "LOOT_504"
#define UNSTABLE_EVOLUTION_TOKEN "LOOT_504t"
#define LORD_JARAXXUS "EX1_323"
#define LORD_JARAXXUS_HERO "EX1_323h"
#define MAJORDOMO_EXECUTUS "BRM_027"
#define MAJORDOMO_EXECUTUS_HERO "BRM_027h"
#define MALFURION_THE_PESTILENT "ICC_832"
#define DEATHSTALKER_REXXAR "ICC_828"
#define FROST_LICH_JAINA "ICC_833"
#define UTHER_OF_THE_EBON_BLADE "ICC_829"
#define SHADOWREAPER_ANDUIN "ICC_830"
#define VALEERA_THE_HOLLOW "ICC_827"
#define THRALL_DEATHSEER "ICC_481"
#define BLOODREAVER_GULDAN "ICC_831"
#define SCOURGELORD_GARROSH "ICC_834"
#define HALLAZEAL_THE_ASCENDED "OG_209"
#define LESSER_MITHRIL_SPELLSTONE "LOOT_203"
#define PSYCHIC_SCREAM "LOOT_008"
#define LESSER_JASPER_SPELLSTONE "LOOT_051"
#define SECOND_RATE_BRUISER "CFM_652"
#define CINDERSTORM "GIL_147"
#define CURSED_CASTAWAY "GIL_557"
#define BOGSHAPER "GIL_807"
#define TOWN_CRIER "GIL_580"
#define DOLLMASTER_DORIAN "GIL_620"
#define COUNTESS_ASHMORE "GIL_578"
#define SANDBINDER "GIL_581"
#define WITCHWOOD_PIPER "GIL_584"
#define SEA_GIANT "EX1_586"
#define PRIMORDIAL_GLYPH "UNG_941"
#define BLOODBLOOM "UNG_832"
#define FAR_SIGHT "CS2_053"
#define GRASP_THE_FUTURE "TOT_103"
#define TIMEBOUND_GIANT "TOT_110"
#define TIMEWAY_WANDERER "TOT_116"
#define METEOROLOGIST "BOT_601"
#define GLOWSTONE_TECHNICIAN "BOT_910"
#define SOUL_INFUSION "BOT_263"


#endif // CONSTANTS_H
