#ifndef THEMEHANDLER_H
#define THEMEHANDLER_H

#include <QString>
#include <QJsonObject>
#include "utility.h"

class ThemeHandler
{

//Variables
private:
    static QString bgApp_;
    static QString borderApp_;
    static QString borderTransparent_;
    static int borderWidth_;
    static QString fgColor_;
    static QString themeColor1_;
    static QString themeColor2_;
    static QString bgWidgets_;
    static QString bgTabsColor_, hoverTabsColor_, selectedTabsColor_;
    static QString bgTopButtonsColor_, hoverTopButtonsColor_;
    static QString synergyTagColor_;
    static QString fgMenuColor_, bgMenuColor_;
    static QString bgSelectedItemMenuColor_, fgSelectedItemMenuColor_;
    static int borderDecksWidth_;
    static QString bgDecks_, borderDecks_;
    static QString bgSelectedItemListColor_, fgSelectedItemListColor_;
    static QString borderTooltipColor_, bgTooltipColor_, fgTooltipColor_;
    static QString borderProgressBarColor_, bgProgressBarColor_, fgProgressBarColor_, chunkProgressBarColor_;
    static QString borderLineEditColor_, bgLineEditColor_, fgLineEditColor_;
    static QString bgSelectionLineEditColor_, fgSelectionLineEditColor_;
    static QString defaultFont_, cardsFont_, bigFont_;
    static int cardsFontOffsetY_;
    static QString tabArenaFile_, tabConfigFile_, tabDeckFile_, tabEnemyDeckFile_, tabGraveyardFile_;
    static QString tabGamesFile_, tabHandFile_, tabLogFile_, tabPlanFile_;
    static QString buttonRemoveDeckFile_, buttonLoadDeckFile_, buttonNewDeckFile_, buttonSaveDeckFile_;
    static QString buttonMinFile_, buttonPlusFile_, buttonRemoveFile_;
    static QString buttonCloseFile_, buttonMinimizeFile_, buttonResizeFile_;
    static QString buttonForceDraftFile_, buttonDraftRefreshFile_;
    static QString buttonGamesReplayFile_, buttonGamesWebFile_, buttonGamesGuideFile_;
    static QString buttonPlanFirstFile_, buttonPlanLastFile_, buttonPlanRefreshFile_;
    static QString buttonPlanPrevFile_, buttonPlanNextFile_, buttonPlanResizeFile_;
    static QString buttonGraveyardPlayerFile_, buttonGraveyardEnemyFile_;
    static QString buttonGraveyardAllFile_, buttonGraveyardMinionsFile_, buttonGraveyardWeaponsFile_, buttonGraveyardSpellsFile_;
    static QString bgCard1Files_[NUM_HEROS+1], bgCard2Files_[NUM_HEROS+1], heroFiles_[NUM_HEROS];
    static QString bgTotalAttackFile_;
    static QString branchClosedFile_, branchOpenFile_;
    static QString coinFile_, firstFile_;
    static QString loseFile_, winFile_;
    static QString haBestFile_, haCloseFile_, haOpenFile_, haTextFile_;
    static QString lfBestFile_, lfCloseFile_, lfOpenFile_, lfTextFile_;
    static QString hsrBestFile_, hsrCloseFile_, hsrOpenFile_, hsrTextFile_, youTextFile_;
    static QString speedLavaFile_, speedCloseFile_, speedOpenFile_;
    static QString speedDWTextFile_, speedTwitchTextFile_;
    static QString handCardFile_, handCardBYFile_, handCardBYFile2_, handCardBYUnknownFile_;
    static QString starFile_, manaLimitFile_, unknownFile_;
    static QString minionsCounterFile_, spellsCounterFile_, weaponsCounterFile_, manaCounterFile_;
    static QString drop2CounterFile_, drop3CounterFile_, drop4CounterFile_;
    static QString aoeMechanicFile_, tauntMechanicFile_, survivalMechanicFile_, drawMechanicFile_;
    static QString pingMechanicFile_, damageMechanicFile_, destroyMechanicFile_, reachMechanicFile_;
    static QString checkCardOkFile_, goldenMechanicFile_, greenMechanicFile_, redMechanicFile_;
    static QString bgDraftMechanicsFile_, bgDraftMechanicsHelpFile_, bgDraftMechanicsHelpDropsFile_, fgDraftMechanicsColor_;
    static bool manaLimitBehind_;
    static QString themeLoaded_;


//Metodos
private:
    static void loadThemeValues(const QString &themePath, QByteArray &jsonData);
    static QString loadThemeFile(const QString &themePath, QJsonObject &jsonObject, const QString &key);
    static QString loadThemeCF(const QString &themePath, QJsonObject &jsonObject, const QString &key);    
    static QString loadThemeFont(const QString &themePath, QJsonObject &jsonObject, const QString &key);

public:
    static bool loadTheme(QString theme);
    static void defaultEmptyValues();
    static QString bgApp();
    static QString borderApp(bool transparent);
    static int borderWidth();
    static QString fgColor();
    static QString themeColor1();
    static QString themeColor2();
    static QString bgWidgets();
    static QString bgTabsColor();
    static QString hoverTabsColor();
    static QString selectedTabsColor();
    static QString bgTopButtonsColor();
    static QString hoverTopButtonsColor();
    static QString synergyTagColor();
    static QString fgMenuColor();
    static QString bgSelectedItemMenuColor();
    static QString fgSelectedItemMenuColor();
    static QString bgMenuColor();
    static QString bgDecks();
    static QString borderDecks();
    static QString bgSelectedItemListColor();
    static QString fgSelectedItemListColor();
    static QString borderTooltipColor();
    static QString bgTooltipColor();
    static QString fgTooltipColor();
    static QString borderProgressBarColor();
    static QString bgProgressBarColor();
    static QString fgProgressBarColor();
    static QString chunkProgressBarColor();
    static QString borderLineEditColor();
    static QString bgLineEditColor();
    static QString fgLineEditColor();
    static QString bgSelectionLineEditColor();
    static QString fgSelectionLineEditColor();
    static QString defaultFont();
    static QString cardsFont();
    static QString bigFont();
    static int cardsFontOffsetY();
    static QString tabArenaFile();
    static QString bgCard1File(int order=NUM_HEROS);
    static QString bgCard2File(int order=NUM_HEROS);
    static QString branchClosedFile();
    static QString branchOpenFile();
    static QString buttonRemoveDeckFile();
    static QString buttonCloseFile();
    static QString coinFile();
    static QString tabConfigFile();
    static QString tabDeckFile();
    static QString buttonForceDraftFile();
    static QString buttonDraftRefreshFile();
    static QString tabEnemyDeckFile();
    static QString tabGraveyardFile();
    static QString firstFile();
    static QString tabGamesFile();
    static QString haBestFile();
    static QString haCloseFile();
    static QString tabHandFile();
    static QString handCardFile();
    static QString handCardBYFile();
    static QString handCardBYFile2();
    static QString handCardBYUnknownFile();
    static QString haOpenFile();
    static QString haTextFile();
    static QString heroFile(int order);
    static QString heroFile(QString heroLog);
    static QString starFile();
    static QString lfBestFile();
    static QString lfCloseFile();
    static QString lfOpenFile();
    static QString lfTextFile();
    static QString hsrBestFile();
    static QString hsrCloseFile();
    static QString hsrOpenFile();
    static QString hsrTextFile();
    static QString youTextFile();
    static QString speedLavaFile();
    static QString speedCloseFile();
    static QString speedOpenFile();
    static QString speedDWTextFile();
    static QString speedTwitchTextFile();
    static QString buttonLoadDeckFile();
    static QString tabLogFile();
    static QString loseFile();
    static QString manaLimitFile();
    static QString buttonMinimizeFile();
    static QString buttonMinFile();
    static QString buttonNewDeckFile();
    static QString tabPlanFile();
    static QString buttonPlanFirstFile();
    static QString buttonPlanLastFile();
    static QString buttonPlanRefreshFile();
    static QString buttonPlanPrevFile();
    static QString buttonPlanNextFile();
    static QString buttonPlanResizeFile();
    static QString buttonGraveyardPlayerFile();
    static QString buttonGraveyardEnemyFile();
    static QString buttonGraveyardAllFile();
    static QString buttonGraveyardMinionsFile();
    static QString buttonGraveyardWeaponsFile();
    static QString buttonGraveyardSpellsFile();
    static QString buttonPlusFile();
    static QString buttonRemoveFile();
    static QString buttonGamesReplayFile();
    static QString buttonResizeFile();
    static QString buttonSaveDeckFile();
    static QString unknownFile();
    static QString buttonGamesWebFile();
    static QString buttonGamesGuideFile();
    static QString winFile();
    static QString bgTotalAttackFile();
    static bool manaLimitBehind();
    static QString themeLoaded();
    static QString minionsCounterFile();
    static QString spellsCounterFile();
    static QString weaponsCounterFile();
    static QString manaCounterFile();
    static QString drop2CounterFile();
    static QString drop3CounterFile();
    static QString drop4CounterFile();
    static QString aoeMechanicFile();
    static QString tauntMechanicFile();
    static QString survivalMechanicFile();
    static QString drawMechanicFile();
    static QString pingMechanicFile();
    static QString damageMechanicFile();
    static QString destroyMechanicFile();
    static QString reachMechanicFile();
    static QString checkCardOkFile();
    static QString goldenMechanicFile();
    static QString greenMechanicFile();
    static QString redMechanicFile();
    static QString bgDraftMechanicsFile();
    static QString fgDraftMechanicsColor();
    static QString bgDraftMechanicsHelpFile();
    static QString bgDraftMechanicsHelpDropsFile();
};

#endif // THEMEHANDLER_H
